imports:
    - { resource: "services/forms.yml" }
    - { resource: "services/installer.yml" }

services:
    _defaults:
        public: true

    ### Registries
    process_manager_queue.registry.queue:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerQueueBundle\Queue\QueueInterface
            - 'Process Manager Queues'

    process_manager_queue.registry.queue_handler_factories:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - ProcessManagerBundle\Monolog\HandlerFactoryInterface
            - 'Handler Factories'

    process_manager_queue.form.registry.queue:
        class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    process_manager_queue.event_listener.cron:
        class: ProcessManagerQueueBundle\EventListener\CronListener
        tags:
            - { name: kernel.event_listener, event: pimcore.system.maintenance, method: run, arguments: }
            - { name: monolog.logger, channel: process_manager_queue.cron }
        arguments:
            - '@process_manager.registry.processes'
